944 streamline secir python code
SciCompMod/memilio pull request #1041
Opened 2024-05-26 15:04 UTC by MaxBetzDLR

# Changes and Information

Please **briefly list the changes** (main added features, changed items, or corrected bugs) made:

-
-
-

If need be, add additional information and what the reviewer should look out for in particular:

-
-

## Merge Request - Guideline Checklist

Please check our [git workflow](https://github.com/SciCompMod/memilio/wiki/git-workflow). Use the **draft** feature if the Pull Request is not yet ready to review.

### Checks by code author

- [ ] Every addressed issue is linked (use the "Closes #ISSUE" keyword below)
- [ ] New code adheres to [coding guidelines](https://github.com/SciCompMod/memilio/wiki/Coding-guidelines)
- [ ] No large data files have been added (files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [ ] Tests are added for new functionality and a local test run was successful (with and without OpenMP)
- [ ] Appropriate **documentation** for new functionality has been added (Doxygen in the code and Markdown files if necessary)
- [ ] Proper attention to licenses, especially no new third-party software with conflicting license has been added
- [ ] (For ABM development) Checked [benchmark results](https://github.com/SciCompMod/memilio/wiki/Agent-Based-Model-Development) and ran and posted a local test above from before and after development to ensure performance is monitored.

### Checks by code reviewer(s)

- [ ] Corresponding issue(s) is/are linked and addressed
- [ ] Code is clean of development artifacts (no deactivated or commented code lines, no debugging printouts, etc.)
- [ ] Appropriate **unit tests** have been added, CI passes, code coverage and performance is acceptable (did not decrease)
- [ ] No large data files added in the whole history of commits(files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [ ] On merge, add 2-5 lines with the changes (main added features, changed items, or corrected bugs) to the merge-commit-message. This can be taken from the **briefly-list-the-changes** above (best case) or the separate commit messages (worst case).

2024-05-28 06:30 UTC, HenrZu requested changes
Thank you for these changes :) Some comments and then it can be merged

2024-05-28 06:30 UTC, HenrZu commented on pycode/examples/simulation/migration.py
> +        description='Example demonstrating the setup and simulation of a geographically resolved ODE SECIHURD model with travel.')
```suggestion
        description='Example demonstrating the setup and simulation of a geographically resolved ODE SECIHURD model with mobility.')
```

2024-05-28 06:30 UTC, HenrZu commented on pycode/memilio-simulation/memilio/simulation/osecir.cpp
>      //normally, std::vector is bound to any python iterable, but this doesn't work for move-only elements
change line 260 to:
// These functions are in general not <del>secir</del> model dependent, only with the current config.

2024-05-29 11:15 UTC, MaxBetzDLR commented on pycode/memilio-simulation/memilio/simulation_test/test_pickle.py
> +# Authors:
I dont feel confident to add authors to scripts i had nothing to do with. In general it seems ok not to have an author named for every script.

2024-05-29 11:52 UTC, HenrZu approved these changes

2024-05-29 12:19 UTC, merged