1042 stub generation for python bindings
SciCompMod/memilio pull request #1044
Opened 2024-05-28 13:56 UTC by MaxBetzDLR

# Changes and Information

Please **briefly list the changes** (main added features, changed items, or corrected bugs) made:

-
-
-

If need be, add additional information and what the reviewer should look out for in particular:

-
-

## Merge Request - Guideline Checklist

Please check our [git workflow](https://github.com/SciCompMod/memilio/wiki/git-workflow). Use the **draft** feature if the Pull Request is not yet ready to review.

### Checks by code author

- [ ] Every addressed issue is linked (use the "Closes #ISSUE" keyword below)
- [ ] New code adheres to [coding guidelines](https://github.com/SciCompMod/memilio/wiki/Coding-guidelines)
- [ ] No large data files have been added (files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [ ] Tests are added for new functionality and a local test run was successful (with and without OpenMP)
- [ ] Appropriate **documentation** for new functionality has been added (Doxygen in the code and Markdown files if necessary)
- [ ] Proper attention to licenses, especially no new third-party software with conflicting license has been added
- [ ] (For ABM development) Checked [benchmark results](https://github.com/SciCompMod/memilio/wiki/Agent-Based-Model-Development) and ran and posted a local test above from before and after development to ensure performance is monitored.

### Checks by code reviewer(s)

- [x] Corresponding issue(s) is/are linked and addressed
- [x] Code is clean of development artifacts (no deactivated or commented code lines, no debugging printouts, etc.)
- [x] Appropriate **unit tests** have been added, CI passes, code coverage and performance is acceptable (did not decrease)
- [x] No large data files added in the whole history of commits(files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [x] On merge, add 2-5 lines with the changes (main added features, changed items, or corrected bugs) to the merge-commit-message. This can be taken from the **briefly-list-the-changes** above (best case) or the separate commit messages (worst case).

Closes #1042

2024-06-06 08:01 UTC, reneSchm requested changes
Looks good, I mostly have small comments on the documentation.

2024-06-10 11:05 UTC, MaxBetzDLR commented on pycode/memilio-simulation/CMakeLists.txt
> +endfunction()
Thats just a shorthand, which was usefull when i tried to add the stubgen to cmake and still makes adding a new module less redundant. In our current structure it is guaranteed that all targets need the same includes.

2024-06-10 11:06 UTC, MaxBetzDLR commented on pycode/memilio-simulation/README.md
> +For installation you need to have `memilio.simulation` and `pybind11-stubgen` installed for your python interpreter. Then run [generate_stubs.py](tools/generate_stubs.py) to generate the stubs-only p
Yes, it should make clear that this module is needed and not any other memilio module like memilio.epidata.

2024-06-10 11:14 UTC, MaxBetzDLR commented on pycode/memilio-simulation/setup.py
> +    package_data={"memilio.simulation": ["py.typed"]})
That is the marker file to support typing, but isnt needed anymore due to distributing the stubs in a a stub-only package (https://peps.python.org/pep-0561/#stub-only-packages). I removed it.

2024-06-10 11:17 UTC, MaxBetzDLR commented on pycode/memilio-simulation/tools/generate_stubs.py
> +        os.makedirs(output_dir)
No, the output_module_dir is generated by pybind11_stubgen. The intention was to create the root folder for the output.

2024-06-10 11:38 UTC, MaxBetzDLR commented on pycode/memilio-simulation/tools/generate_stubs.py
> +models = ["osir", "oseir", "osecir", "osecirvvs", "abm"]
Changed this, so models get detected via the python package structure of memilio.simulation

2024-06-10 11:41 UTC, reneSchm commented on pycode/memilio-simulation/README.md
> +For installation you need to have `memilio.simulation` and `pybind11-stubgen` installed for your python interpreter. Then run [generate_stubs.py](tools/generate_stubs.py) to generate the stubs-only p
Okay, then my suggestion should read "install our module" instead of package, correct?

2024-06-10 11:45 UTC, reneSchm commented on pycode/memilio-simulation/CMakeLists.txt
> +endfunction()
Then it is fine to keep. Even if the configuration is redundant, I think it is often useful to keep it close to the targets so it is easier to maintain, especially when using multiple cmake files.

2024-06-10 11:46 UTC, reneSchm commented on pycode/memilio-simulation/setup.py
> +    package_data={"memilio.simulation": ["py.typed"]})
That works too :)

2024-06-10 12:02 UTC, reneSchm commented on pycode/memilio-simulation/tools/generate_stubs.py
> +        os.makedirs(output_dir)
Okay. Maybe add a small comment to that.

2024-06-10 12:41 UTC, reneSchm commented on pycode/memilio-simulation/setup.py
>      long_description='', test_suite='memilio.simulation_test',
Here is a trailing comma

2024-06-10 12:48 UTC, MaxBetzDLR commented on pycode/memilio-simulation/setup.py
>      long_description='', test_suite='memilio.simulation_test',
Thats common and not a problem

2024-06-10 13:19 UTC, reneSchm approved these changes

2024-06-10 13:24 UTC, merged