Fix a "use after free" warning with gcc 12.3.0 and above
SciCompMod/memilio pull request #1060
Opened 2024-06-27 13:28 UTC by reneSchm

# Changes and Information

Please **briefly list the changes** (main added features, changed items, or corrected bugs) made:

- Fix a "use after free" warning with gcc 12.3. and above.
-
-

If need be, add additional information and what the reviewer should look out for in particular:

-
-

## Merge Request - Guideline Checklist

Please check our [git workflow](https://github.com/SciCompMod/memilio/wiki/git-workflow). Use the **draft** feature if the Pull Request is not yet ready to review.

### Checks by code author

- [ ] Every addressed issue is linked (use the "Closes #ISSUE" keyword below)
- [ ] New code adheres to [coding guidelines](https://github.com/SciCompMod/memilio/wiki/Coding-guidelines)
- [ ] No large data files have been added (files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [ ] Tests are added for new functionality and a local test run was successful (with and without OpenMP)
- [ ] Appropriate **documentation** for new functionality has been added (Doxygen in the code and Markdown files if necessary)
- [ ] Proper attention to licenses, especially no new third-party software with conflicting license has been added
- [ ] (For ABM development) Checked [benchmark results](https://github.com/SciCompMod/memilio/wiki/Agent-Based-Model-Development) and ran and posted a local test above from before and after development to ensure performance is monitored.

### Checks by code reviewer(s)

- [ ] Corresponding issue(s) is/are linked and addressed
- [ ] Code is clean of development artifacts (no deactivated or commented code lines, no debugging printouts, etc.)
- [ ] Appropriate **unit tests** have been added, CI passes, code coverage and performance is acceptable (did not decrease)
- [ ] No large data files added in the whole history of commits(files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [ ] On merge, add 2-5 lines with the changes (main added features, changed items, or corrected bugs) to the merge-commit-message. This can be taken from the **briefly-list-the-changes** above (best case) or the separate commit messages (worst case).

2024-06-28 16:07 UTC, dabele requested changes

2024-06-28 16:08 UTC, dabele commented on cpp/memilio/epidemiology/damping.h
> +        Matrix sum = std::get<Matrix>(v.front());
note to self, sometimes obsessive use of `auto` leads to less readable code. your version is clearer but equivalent.

2024-07-01 10:23 UTC, reneSchm commented on cpp/memilio/epidemiology/damping.h
> +            sum = (sum + std::get<Matrix>(*b) - (sum.array() * std::get<Matrix>(*b).array()).matrix()).eval();
The use after free only appears when compiling in Release mode, and at first I only saw it in a py-simulation CI. It also does not get diagnosed in the inclusive_exclusive_sum function, but in the update_cache when assigning "combined_damping".

The diagnostic (for me) did not change at all using all expressions, but the compiler gets confused somewhere during the array_prod or mat_prod part, so I kept only that one. 

I thought the assignment to sum would already trigger an eval, but Matrix might be a temporary as well, right?

2024-07-03 16:20 UTC, dabele commented on cpp/memilio/epidemiology/damping.h
> +            sum = (sum + std::get<Matrix>(*b) - (sum.array() * std::get<Matrix>(*b).array()).matrix()).eval();
I find it's safe to assume Eigen doesn't allocate unless it has to (e.g. A * B * C with matrix matrix multiplication needs temporary storage of A * B) or it is explicitly told to (e.g. eval() or constructors). Here, it can just write element-wise directly into the storage of `sum`.

2024-07-03 16:43 UTC, dabele approved these changes

2024-07-03 16:44 UTC, merged