646 use graph model with ABMs v3
SciCompMod/memilio pull request #1085
Opened 2024-08-01 13:00 UTC by jubicker

# Changes and Information

Please **briefly list the changes** (main added features, changed items, or corrected bugs) made:

- add node property and edge property class for ABM graph simulation
- add model wrapper for abm that is used for ABM graph simulation and can handle persons that commute to other nodes
- add tests for new functionality
- add graph abm example

## Merge Request - Guideline Checklist

Please check our [git workflow](https://github.com/SciCompMod/memilio/wiki/git-workflow). Use the **draft** feature if the Pull Request is not yet ready to review.

### Checks by code author

- [x] Every addressed issue is linked (use the "Closes #ISSUE" keyword below)
- [x] New code adheres to [coding guidelines](https://github.com/SciCompMod/memilio/wiki/Coding-guidelines)
- [x] No large data files have been added (files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [x] Tests are added for new functionality and a local test run was successful (with and without OpenMP)
- [x] Appropriate **documentation** for new functionality has been added (Doxygen in the code and Markdown files if necessary)
- [x] Proper attention to licenses, especially no new third-party software with conflicting license has been added
- [x] (For ABM development) Checked [benchmark results](https://github.com/SciCompMod/memilio/wiki/Agent-Based-Model-Development) and ran and posted a local test above from before and after development to ensure performance is monitored.

### Checks by code reviewer(s)

- [x] Corresponding issue(s) is/are linked and addressed
- [x] Code is clean of development artifacts (no deactivated or commented code lines, no debugging printouts, etc.)
- [x] Appropriate **unit tests** have been added, CI passes, code coverage and performance is acceptable (did not decrease)
- [x] No large data files added in the whole history of commits(files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [ ] On merge, add 2-5 lines with the changes (main added features, changed items, or corrected bugs) to the merge-commit-message. This can be taken from the **briefly-list-the-changes** above (best case) or the separate commit messages (worst case).

2024-08-08 11:06 UTC, jubicker commented
Performance Measures:
The following are the results of 1 execution of the abm benchmark for a single thread (OMP_NUM_THREADS=1)

Main:

---------------------------------------------------------------------------
Benchmark                                 Time             CPU   Iterations
---------------------------------------------------------------------------
abm_benchmark/abm_benchmark_50k        3487 ms         3486 ms            1
abm_benchmark/abm_benchmark_100k       7698 ms         7695 ms            1
abm_benchmark/abm_benchmark_200k      15922 ms        15917 ms            1

Graph model v3 branch:

 ---------------------------------------------------------------------------
Benchmark                                 Time             CPU   Iterations
---------------------------------------------------------------------------
abm_benchmark/abm_benchmark_50k        3720 ms         3718 ms            1
abm_benchmark/abm_benchmark_100k       7938 ms         7935 ms            1
abm_benchmark/abm_benchmark_200k      16320 ms        16315 ms            1

2025-01-10 13:55 UTC, jubicker commented on cpp/models/abm/person.cpp
> +
I think a change in naming is a good idea, we can discuss that.

To the second part: If I understand you right, this is exact what is done in "add_person".

2025-01-10 14:10 UTC, jubicker commented on cpp/models/graph_abm/model_wrapper.h
> +            }
In the implementation of perform_mobility in model.cpp, fixed mobility rules are executed while for the graph abm, the mobility rules are input to the model. The default value for the m_mobility_rules vector are however the same mobility rules like in the "normal" ABM.

2025-01-10 14:27 UTC, reneSchm commented on cpp/models/abm/person.cpp
> +
Kind of... But I think we should decide either on the World always overwriting the unique ID (like it does with PersonID), or on the World not changing it at all. I feel like changing the ID only when it is invalid can lead to unexpected behaviour, as invalid now means "not set, please overwrite" instead.

2025-01-10 14:32 UTC, jubicker commented on cpp/models/abm/person.cpp
> +
We cannot always overwrite it, because when a person changes the world, then it losses its unique id. What we need to do is only set it, if it has not been set before. I died this using the INVALID_UNIQUE_ID, but I'm open for other solutions :).

2025-01-13 10:39 UTC, DavidKerkmann commented on cpp/models/abm/person.cpp
> +
I think the global ID is meant to be set only once, when the person first enters the simulations and is assigned a "home world". For me, this changes make sense. Best would be to have the global ID const, which is initialized during the Person constructor, but this would change the add_person structure. We could make some struct that only allows for a one-time modification and then being const. But there might be better solutions.

2025-01-13 11:53 UTC, reneSchm commented on cpp/models/abm/person.cpp
> +
> What we need to do is only set it, if it has not been set before. I did this using the INVALID_UNIQUE_ID

This works now, but the reason we have this invalid id is to signal that something went wrong, hence all the asserts checking for it. If you use it additionally as a "not set" flag, this can potentially end up hiding other problems.

I would be in favor of making it effectively const - an actually const member would be annoying, as we cannot use default move or copy ctors.
Some options would be:
- Setting the UID in main, and removing the UID overwrite from add_person and that Person ctor which copies a Person and assigns a new ID
- using an optional (so we have a "not set" state)
- defining a second value like invalid_id
The latter two options then require checking that the id is both set and valid every time we pass it to a new function. The first requires additional setup outside of the model (which is okay in theory, as it is a "global" id).

All are a bit weird in that we treat the IDs differently. Only one is always being overwritten by the world, the other only sometimes, or elsewhere.

2025-01-13 15:54 UTC, DavidKerkmann commented on cpp/models/abm/model.cpp
> +        auto& person      = get_person(PersonId(static_cast<uint32_t>(trip.person_id)));
Edit: works for normal ABM without graphs.

2025-01-16 13:35 UTC, DavidKerkmann requested changes
There are only a small things left to improve and one discussion item.

2025-01-16 13:35 UTC, DavidKerkmann commented on cpp/tests/test_graph_abm.cpp
> +TEST(TestGraphABM, mask_compliance)
What is the reason this is a test in the GraphABM compared to the normal one?

2025-01-16 13:36 UTC, DavidKerkmann commented on cpp/models/abm/person_id.h
> +        : mio::TypeSafe<uint64_t, PersonId>(std::numeric_limits<uint32_t>::max())
Changed to GlobalID.

2025-01-16 13:39 UTC, DavidKerkmann commented on cpp/models/abm/model.cpp
> +            if (person.get_location_model_id() == m_id) {
I thought about ONLY checking the activness status, and not the model id. Would that be wrong?

2025-01-16 13:39 UTC, DavidKerkmann commented on cpp/models/abm/model.cpp
> +            if (m_persons[i].get_location_model_id() == m_id) {
I thought about ONLY checking the activness status, and not the model id. Would that be wrong?

2025-01-16 13:45 UTC, DavidKerkmann commented on cpp/models/graph_abm/model_wrapper.h
> +            }
Ah, I see. I think this would make sense to also be used in the "normal" ABM. There, the `m_mobility_rules` is currently unused, which should be changed.

2025-01-16 13:50 UTC, DavidKerkmann commented on cpp/models/graph_abm/model_wrapper.h
> +            auto personal_rng = PersonalRandomNumberGenerator(Base::m_rng, person);
Vector is sorted now, so the adding will always happen in the same order, leading to the same outcome.
No other issues with parallel execution have been detected so far.
Perhaps it would still be good to add a test for that: For example, make 1.000 random persons for multiple nodes in a graph and exchange wildly, using OpenMP in each node.

2025-01-16 13:52 UTC, DavidKerkmann commented on cpp/models/abm/person.h
> +                    int location_model_id, AgeGroup age, PersonId person_id = PersonId::invalid_id());
Discussed that this could be done, but could also lead to errors if not being careful with adding Persons and Locations incorrectly. Thus, this is left as it is.

2025-01-16 14:01 UTC, DavidKerkmann commented on cpp/models/graph_abm/graph_abm_mobility.h
> +    std::tuple<History...> m_history;
This was thoroughly discussed. We didn't find a good solution, as changing histories may become difficult in other parts. We stay with this concept for now.

2025-01-16 14:01 UTC, DavidKerkmann commented on cpp/models/graph_abm/graph_abm_mobility.h
> +    void evolve(mio::abm::TimePoint t, mio::abm::TimeSpan dt)
Renamed to advance as suggested.

2025-01-20 12:54 UTC, jubicker commented on cpp/tests/test_graph_abm.cpp
> +TEST(TestGraphABM, mask_compliance)
The test is actually the same, but as we have an own perform_mobility function in the GraphABM which implements the same mask behavior as the "normal" perform_mobility, we need to implement the same test for that function.

2025-01-20 13:02 UTC, jubicker commented on cpp/models/graph_abm/model_wrapper.h
> +            auto personal_rng = PersonalRandomNumberGenerator(Base::m_rng, person);
We test whether the sorting works in test_apply_mobility

2025-01-20 13:07 UTC, jubicker commented on cpp/models/abm/model.cpp
> +            if (m_persons[i].get_location_model_id() == m_id) {
I think checking both is necesary, because even if the activeness status is true, what do we do with a person that is currently in another world? Of course this should never happen, but checking both makes sure we do not do something undefined if we however have that.

2025-01-20 14:00 UTC, reneSchm commented on cpp/models/abm/model.cpp
> +            if (m_persons[i].get_location_model_id() == m_id) {
If you are sure that it never happens (assuming the initialization was good), using an assert to check the world id would be okay, I think

2025-01-20 14:40 UTC, DavidKerkmann commented on cpp/models/abm/person.h
> -            .add("index", m_person_index)
We might have to add the new data members to this list.

2025-01-20 14:40 UTC, DavidKerkmann commented on cpp/models/abm/person.h
> +    uint32_t m_rng_index;
Ah, I see. Well now instead of the person index we have the rng index.

In all current use cases, we could use the other constructor of PersonalRNG that uses the index directly from its index in the world. However, when we want to construct the PersonalRNG inside the Person or anywhere where the world is not known, this is a problem.

Further, this rng_index needs to be updated each time a person is removed and added to a world, such that it uses the correct world index and doesn't clash with the same rng_index of another person.

Let's discuss in the next meeting.

2025-01-20 14:40 UTC, DavidKerkmann commented on cpp/models/graph_abm/graph_abmodel.h
> +    void update_person_indices()
This got changed such that each person doesn't save its own index anymore.

2025-01-20 14:41 UTC, DavidKerkmann reviewed
Thanks! Only one point left to discuss from my side.

2025-01-23 13:10 UTC, DavidKerkmann commented on cpp/models/abm/person.cpp
> +
Only one ID is used after the changes, so this is outdated.

2025-01-23 14:48 UTC, jubicker commented on cpp/memilio/mobility/graph_simulation.h
> +    void advance(Timepoint t_max = 1.0)
Before both advance functions (of the normal GraphSimulation and the GraphSimulationStochastic) got a double as input. Therefore the right "advance" was automatically taken by the GraphSimulationStochastic, which is not ensured any more when keeping the function in the Base class due to the template. If we kept this function in the Base class it would be possible for a GraphSimulationStochastic object to call the wrong advance function using abm::TimePoint instead of double as input.

2025-01-23 14:52 UTC, jubicker commented on cpp/models/graph_abm/model_wrapper.h
> +                    Base::m_activeness_statuses[person_index] = false;
We decided to leave it like this and leave it up to the user how often agents are exchanged between nodes as the appropriate frequency of exchanging agents depends heavily on the concrete application. Otherwise we would destroy the runtime advance of the GraphABM compared to the normal ABM.

2025-01-23 15:00 UTC, jubicker commented on cpp/models/graph_abm/model_wrapper.h
> +            }
I opened an issue for this, see #1199

2025-01-24 08:03 UTC, reneSchm commented on cpp/memilio/mobility/graph_simulation.h
> +    void advance(Timepoint t_max = 1.0)
Would it make more sense to change GraphSimulationBase::advance from double to Timepoint? It does use Timepoint for m_t already.

2025-01-24 08:28 UTC, jubicker commented on cpp/memilio/mobility/graph_simulation.h
> +    void advance(Timepoint t_max = 1.0)
Do you mean GraphSimulationStochastic? GraphSimulationBase does not have an advance function any more.

2025-01-30 09:38 UTC, DavidKerkmann requested changes
Almost everything has been resolved, I only have requests for small stylistic changes.

2025-01-30 09:38 UTC, DavidKerkmann commented on cpp/models/abm/person.h
> +     * @brief Get this persons index that is used for the RandomNumberGenerator.
```suggestion
     * @brief Get this Person's index that is used for the RandomNumberGenerator.
```

2025-01-30 09:38 UTC, DavidKerkmann commented on cpp/models/abm/person.h
> +     * @brief Get this person's key that is used for the RandomNumberGenerator.
```suggestion
     * @brief Get this Person's key that is used for the RandomNumberGenerator.
```

2025-01-30 09:38 UTC, DavidKerkmann commented on cpp/models/abm/person.h
> +    mio::Key<uint64_t> m_rng_key; ///< Key for PersonalRandomNumberGenerator
I think it would be good to group these two with the rng_counter in the order key, index, counter, to have better semantic ordering.

2025-01-30 09:38 UTC, DavidKerkmann commented on cpp/models/graph_abm/graph_abmodel.h
> +        }
This if clause should be unnecessary, as the result will always be false. (So just keep line 74.)

2025-01-30 09:38 UTC, DavidKerkmann commented on cpp/models/abm/person.h
> +    uint32_t m_rng_index;
We decided to save all information in the person to keep access to the same RNG, even after the person moved between models.

2025-01-30 10:47 UTC, DavidKerkmann approved these changes

2025-01-31 11:51 UTC, reneSchm commented on cpp/models/abm/model.h
> +            return *it;
This is bad, if itr points to end(), i.e. one position *after* m_persons, you still return *itr, i.e. a Person& to nothing - at least no valid storage. This code should fail after the warning.

2025-01-31 11:54 UTC, reneSchm commented on cpp/models/abm/model.h
> +     * @return A reference to the Person.
```suggestion
     * This function needs to use a template to deduce whether the model and returned person should be const.
     * @param[in] m A reference to `*this`, so we can access m_persons.
     * @param[in] person_id A Person's PersonId.
     * @return A reference to the Person with matching ID.
```
I think this can be more specific

2025-01-31 12:11 UTC, reneSchm commented on cpp/models/abm/model.h
> +            return *it;
Yes. I pretty sure we can't recover if the requested ID is not available during simulation. 
Maybe it could be nice to have a function to test whether an ID is available for the setup, but we don't need it right now.

2025-01-31 13:53 UTC, reneSchm approved these changes

2025-01-31 15:24 UTC, merged