1081 rework abm state transitions
SciCompMod/memilio pull request #1107
Opened 2024-08-13 09:56 UTC by jubicker

# Changes and Information

Please **briefly list the changes** (main added features, changed items, or corrected bugs) made:

-
-
-

If need be, add additional information and what the reviewer should look out for in particular:

-
-

## Merge Request - Guideline Checklist

Please check our [git workflow](https://github.com/SciCompMod/memilio/wiki/git-workflow). Use the **draft** feature if the Pull Request is not yet ready to review.

### Checks by code author

- [ ] Every addressed issue is linked (use the "Closes #ISSUE" keyword below)
- [ ] New code adheres to [coding guidelines](https://github.com/SciCompMod/memilio/wiki/Coding-guidelines)
- [ ] No large data files have been added (files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [ ] Tests are added for new functionality and a local test run was successful (with and without OpenMP)
- [ ] Appropriate **documentation** for new functionality has been added (Doxygen in the code and Markdown files if necessary)
- [ ] Proper attention to licenses, especially no new third-party software with conflicting license has been added
- [ ] (For ABM development) Checked [benchmark results](https://github.com/SciCompMod/memilio/wiki/Agent-Based-Model-Development) and ran and posted a local test above from before and after development to ensure performance is monitored.

### Checks by code reviewer(s)

- [ ] Corresponding issue(s) is/are linked and addressed
- [ ] Code is clean of development artifacts (no deactivated or commented code lines, no debugging printouts, etc.)
- [ ] Appropriate **unit tests** have been added, CI passes, code coverage and performance is acceptable (did not decrease)
- [ ] No large data files added in the whole history of commits(files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [ ] On merge, add 2-5 lines with the changes (main added features, changed items, or corrected bugs) to the merge-commit-message. This can be taken from the **briefly-list-the-changes** above (best case) or the separate commit messages (worst case).

coses #1081

2025-01-09 14:00 UTC, DavidKerkmann requested changes
Thank you for the implementation!
Apart from some smaller things, we could talk again about the detailed implementation of the distributions, I think @reneSchm will have some more comments and ideas once he has taken a deeper look. Many lines from the param distribtuions are listed as not tested, this could be fixed afterwards.
Related issues that will be closed should be linked correctly. We can have a look together, so that we also know what has to be done next.

2025-01-09 14:00 UTC, DavidKerkmann commented on cpp/tests/test_abm_model.cpp
> +    data.use_weekday_trips_on_weekend();
```suggestion
```
Duplication?

2025-01-09 14:00 UTC, DavidKerkmann commented on cpp/tests/test_abm_model.cpp
> +    // Mock the distribution to prevent infectionsin the test.
```suggestion
    // Mock the distribution to prevent infections in the test.
```

2025-01-10 09:27 UTC, DavidKerkmann commented
My suggestion is to close
#811 and #664 
while
#1081 and #688 
include the symptomatic state inclusion/seperation, which is not covered here.

2025-01-15 10:23 UTC, reneSchm commented on cpp/memilio/utils/parameter_distribution_wrapper.h
> +        return m_dist->params();
Logging is not enough here, as a nullptr dereference is undefined behaviour. If we are lucky, this return will immediately cause a segfault and crash.

2025-02-19 13:10 UTC, jubicker commented on cpp/simulations/abm_braunschweig.cpp
> +    params.get<mio::abm::DeathsPerInfectedCritical>()[{mio::abm::VirusVariant::Wildtype, age_group_60_to_79}] = 0.023;
As all simulations should be moved to the memilio-simulation repo, I think we do not need to update this simulation here.

2025-02-19 13:12 UTC, jubicker commented on cpp/memilio/utils/parameter_distribution_wrapper.h
> +        if (type.value() == "Uniform") {
I'm not aware of any. But as adding new distributions happens very rarely, I think this is okay.

2025-03-26 12:13 UTC, jubicker commented
Benchmark results

Main:
```
---------------------------------------------------------------------------
Benchmark                                 Time             CPU   Iterations
---------------------------------------------------------------------------
abm_benchmark/abm_benchmark_50k        3674 ms         3674 ms            1
abm_benchmark/abm_benchmark_100k       7194 ms         7194 ms            1
abm_benchmark/abm_benchmark_200k      15479 ms        15479 ms            1
```

Branch:
```
---------------------------------------------------------------------------
Benchmark                                 Time             CPU   Iterations
---------------------------------------------------------------------------
abm_benchmark/abm_benchmark_50k        4225 ms         4225 ms            1
abm_benchmark/abm_benchmark_100k       8582 ms         8582 ms            1
abm_benchmark/abm_benchmark_200k      18787 ms        18786 ms            1
```

2025-04-04 09:50 UTC, DavidKerkmann requested changes
Thank you for the improvements. As discussed, only a handful of smaller items to be resolved.

2025-04-07 08:21 UTC, jubicker commented on cpp/models/abm/parameters.h
> +    using Type = CustomIndexArray<UniformDistribution<double>::ParamType, VirusVariant, AgeGroup>;
Yes we can, but do we want to have arbitrary distributions for these parameters?

2025-04-16 08:00 UTC, DavidKerkmann approved these changes
Thanks for resolving the remaining issues. Good to merge from my side.

2025-04-16 08:03 UTC, merged