1019 Adjust memilio-generation for flow models and automatic differentiation
SciCompMod/memilio pull request #1153
Opened 2024-12-02 13:20 UTC by dr2001dlr

# Changes and Information

Please **briefly list the changes** (main added features, changed items, or corrected bugs) made:

-Scanner now checks for Flowmodel and Compartmentalmodel
-pymio includes fixed in template_string
-config.json does not need age_group, simulation and parameterset_wrapper annymore (scanner is setting those)
-added simulate and simulate_flows
-added interpolate_simulation_result and interpolate_ensemble_results
-added scalartype in intermediate_representation to set a datatype for bindings

If need be, add additional information and what the reviewer should look out for in particular:

-Check if the bindings are correct
-

## Merge Request - Guideline Checklist

Please check our [git workflow](https://github.com/SciCompMod/memilio/wiki/git-workflow). Use the **draft** feature if the Pull Request is not yet ready to review.

### Checks by code author

- [ ] Every addressed issue is linked (use the "Closes #ISSUE" keyword below)
- [ ] New code adheres to [coding guidelines](https://github.com/SciCompMod/memilio/wiki/Coding-guidelines)
- [ ] No large data files have been added (files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [ ] Tests are added for new functionality and a local test run was successful (with and without OpenMP)
- [ ] Appropriate **documentation** for new functionality has been added (Doxygen in the code and Markdown files if necessary)
- [ ] Proper attention to licenses, especially no new third-party software with conflicting license has been added
- [ ] (For ABM development) Checked [benchmark results](https://github.com/SciCompMod/memilio/wiki/Agent-Based-Model-Development) and ran and posted a local test above from before and after development to ensure performance is monitored.

### Checks by code reviewer(s)

- [ ] Corresponding issue(s) is/are linked and addressed
- [ ] Code is clean of development artifacts (no deactivated or commented code lines, no debugging printouts, etc.)
- [ ] Appropriate **unit tests** have been added, CI passes, code coverage and performance is acceptable (did not decrease)
- [ ] No large data files added in the whole history of commits(files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [ ] On merge, add 2-5 lines with the changes (main added features, changed items, or corrected bugs) to the merge-commit-message. This can be taken from the **briefly-list-the-changes** above (best case) or the separate commit messages (worst case).

Closes #1019

2025-01-22 12:19 UTC, MaxBetzDLR requested changes

2025-01-22 12:19 UTC, MaxBetzDLR commented on pycode/memilio-generation/memilio/generation/scanner.py
> +            if self.dict.compartmentalmodel in base_name and "mio" in node.semantic_parent.spelling:
'mio' should also be in the default dict

2025-01-22 12:19 UTC, MaxBetzDLR commented on pycode/memilio-generation/memilio/generation_test/dict.json
> +    "parameterspace": "/parameter_space.cpp",
parameter_space is different than all other files. This should be consistent

2025-01-22 12:19 UTC, MaxBetzDLR commented on pycode/memilio-generation/memilio/generation_test/test_data/test_oseir.cpp.txt
> +   return " AgeGroup";
This space in the string is wrong and should not be generated

2025-01-22 12:19 UTC, MaxBetzDLR commented on pycode/memilio-generation/memilio/generation_test/test_data/test_oseir.cpp.txt
> +std::string pretty_name<mio::oseir:: AgeGroup>()
also space before 'AgeGroup'

2025-01-22 12:19 UTC, MaxBetzDLR commented on pycode/memilio-generation/memilio/generation_test/test_data/test_oseir.cpp.txt
> +std::string pretty_name<mio::oseir:: InfectionState>()
space again

2025-01-22 12:19 UTC, MaxBetzDLR commented on pycode/memilio-generation/memilio/generation_test/test_data/test_oseir.cpp.txt
> +    py::class_<mio::oseir::Parameters<double>, pymio::EnablePickling::Required, mio::oseir::ParametersBase<double>>(m, "Parameters");
The following few lines dont seem to be right. There are too many semicolons at the end of lines. Compare it to before.

2025-01-22 12:19 UTC, MaxBetzDLR commented on pycode/memilio-generation/memilio/generation_test/test_oseir_generation.py
> +                # "simulation_name": "",
Remove unused parameters from config files and also the Scanner_config class

2025-01-22 12:19 UTC, MaxBetzDLR commented on pycode/memilio-generation/memilio/tools/config.json
> +        "python_generation_module_path": "/home/rich_dn/repos/memilio/pycode/memilio-generation/../memilio-generation",
i think there are more options that need to be removed or may be unnecessary. Im not shure the use of 'python_generation_module_path' and 'target_folder'. The optional could be removed and just have 'libclang_library_path' at the same level as all other parameters. With 'mio' beeing defined in the dict.json 'namespace' is unnecessary. And 'source_file' and 'python_module_name' may just need to be defined in the example.py, thus three different configs can be merged into one.

2025-01-22 12:19 UTC, MaxBetzDLR commented on pycode/memilio-generation/memilio/tools/config.json
This is a generated file and should not be pushed into the repo. All changes mentioned should be done in the config.json.txt

2025-01-22 12:19 UTC, MaxBetzDLR commented on pycode/memilio-generation/memilio/tools/dict.json
Look into the DEFAULT_DICT inside of memilio-epidata. That may be better than using a json and more clear to use in all parts of the generation.

2025-01-23 09:20 UTC, dr2001dlr commented on pycode/memilio-generation/memilio/generation/scanner.py
> +        s_file = getattr(config, "source_file")
Cant use self.config["source_file"] because "__getitem__" method not defined on type "ScannerConfig". But wasnt the idea to have a variable where the user can write theire source_file_path and then the functions takes it from there?

2025-01-27 07:44 UTC, dr2001dlr commented on pycode/memilio-generation/memilio/tools/dict.json
Created a default_dict.py that replaced the .json

2025-01-27 12:23 UTC, dr2001dlr commented on pycode/memilio-generation/memilio/tools/config.json
> +        "python_generation_module_path": "/home/rich_dn/repos/memilio/pycode/memilio-generation/../memilio-generation",
Removed all unnecessary variables. You can now set the source_file and target_folder in your example. Everthing else is done in the scanner class.

2025-04-07 10:30 UTC, MaxBetzDLR requested changes
Good Code, minor changes to docs

2025-04-07 10:30 UTC, MaxBetzDLR commented on pycode/memilio-generation/memilio/tools/example_oseir.py
> +    home_dir = os.path.expanduser("~")
Maybe just use `file_path = os.path.dirname(os.path.abspath(__file__))` (the tools folder, aka the folder of this file) as the target and point to source file with relative path beginning at `file_path`. Because its not dependent on user specific file structure outside of the package. This seems to expect the package to be in the home folder and cloned in a folder memilio.

2025-04-07 10:30 UTC, MaxBetzDLR commented on pycode/memilio-generation/memilio/tools/README.md
> +## requirements
```suggestion
## Requirements
```

2025-04-07 10:30 UTC, MaxBetzDLR commented on pycode/memilio-generation/memilio/tools/README.md
> +If you want to use the ode_secirvvs model the config should be like this -> `conf.source_file = home_and_user_folder + \ "/memilio/cpp/models/ode_secirvvs/model.cpp"`
string may differ with change in the example

2025-04-07 10:30 UTC, MaxBetzDLR commented on pycode/memilio-generation/memilio/tools/README.md
> +If the terminal shows the memilio package, just give the path with `cd pycode/memilio-generation/memilio/tools`
Should also be in the style of a code block for bash commands

2025-04-07 10:30 UTC, MaxBetzDLR commented on pycode/memilio-generation/memilio/tools/README.md
> +This allows for:
Should that be a list of items?

2025-04-07 10:30 UTC, MaxBetzDLR commented on pycode/memilio-generation/memilio/tools/README.md
> +`aviz.output_ast_png(ast.get_node_by_index(2), 2)` displays the third node of the AST and its children with a depth of 2 as a png file. The second argument of the statement specifies the depth up to
Add a sentence of why the ast needs to be restricted in the png, aka generation time or/and png size

2025-04-07 10:30 UTC, MaxBetzDLR commented on pycode/memilio-generation/memilio/tools/README.md
> +To enable visualization, set the desired method under the `if (print_ast):` statement in the example script.
Maybe rewrite to:
"The visualization is specified under the `if (print_ast):` statement in the example script. It is enabled when running the example with the following command:

2025-04-07 10:30 UTC, MaxBetzDLR commented on pycode/memilio-generation/memilio/tools/README.md
> +## Testing
Testing is not really part of this example and already mentioned in the other README, so you can remove this part

2025-04-07 10:30 UTC, MaxBetzDLR commented on pycode/memilio-generation/memilio/tools/README.md
> +This README provides guidance on how to use the generation package and the visualization features.
You could rewrite this to more specifically explaining the example:
"This README provides guidance on how to use the generation package and the visualization features. 
The explanation follows the example script in [Example](/pycode/memilio-generation/memilio/tools/example_oseir.py). This script allows you to select an ODE model you want to bind, based on the model.cpp from the [Models folder](/cpp/models/..) provided through the corresponding file path."

2025-04-07 10:30 UTC, MaxBetzDLR commented on pycode/memilio-generation/memilio/tools/README.md
> +The package provides an example script in [Example](/pycode/memilio-generation/memilio/tools/example_oseir.py). This script allows you to select which ODE model you want to bind.
If the change above is applied, this part can be removed.

2025-04-07 11:21 UTC, dr2001dlr commented on pycode/memilio-generation/memilio/generation_test/test_oseir_generation.py
> +        self.maxDiff = None
Wenn du self.maxDiff = None setzt, dann wird die komplette Differenz zwischen den beiden Strings im Assertion-Fehler angezeigt, und nicht abgeschnitten. Das brauchst du bei Vergleichen zwischen den Dateien und ist in der unittest.TestCase-Klasse vordefiniert. Ich hatte dass eingefügt damit die Tests wieder richtig laufen, nachdem diese mir Fehler geworfen haben.

2025-04-07 11:29 UTC, dr2001dlr commented on pycode/memilio-generation/memilio/tools/README.md
> +This allows for:
Just a quick description of what you can do with the class.

2025-04-07 11:58 UTC, dr2001dlr commented on pycode/memilio-generation/memilio/generation/scanner.py
>  from memilio.generation import IntermediateRepresentation, utility
Yes but if i do it that way it leads to an circular import

2025-04-07 12:11 UTC, dr2001dlr commented on pycode/memilio-generation/memilio/generation/generator.py
> +        if len(intermed_repr.model_base) > 0:
It is in intermediate representation.

2025-04-28 10:59 UTC, merged