1159 add diffusive abm and smm
SciCompMod/memilio pull request #1162
Opened 2024-12-12 14:03 UTC by jubicker

# Changes and Information

Please **briefly list the changes** (main added features, changed items, or corrected bugs) made:

-
-
-

If need be, add additional information and what the reviewer should look out for in particular:

-
-

## Merge Request - Guideline Checklist

Please check our [git workflow](https://github.com/SciCompMod/memilio/wiki/git-workflow). Use the **draft** feature if the Pull Request is not yet ready to review.

### Checks by code author

- [ ] Every addressed issue is linked (use the "Closes #ISSUE" keyword below)
- [ ] New code adheres to [coding guidelines](https://github.com/SciCompMod/memilio/wiki/Coding-guidelines)
- [ ] No large data files have been added (files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [ ] Tests are added for new functionality and a local test run was successful (with and without OpenMP)
- [ ] Appropriate **documentation** for new functionality has been added (Doxygen in the code and Markdown files if necessary)
- [ ] Proper attention to licenses, especially no new third-party software with conflicting license has been added
- [ ] (For ABM development) Checked [benchmark results](https://github.com/SciCompMod/memilio/wiki/Agent-Based-Model-Development) and ran and posted a local test above from before and after development to ensure performance is monitored.

### Checks by code reviewer(s)

- [ ] Corresponding issue(s) is/are linked and addressed
- [ ] Code is clean of development artifacts (no deactivated or commented code lines, no debugging printouts, etc.)
- [ ] Appropriate **unit tests** have been added, CI passes, code coverage and performance is acceptable (did not decrease)
- [ ] No large data files added in the whole history of commits(files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [ ] On merge, add 2-5 lines with the changes (main added features, changed items, or corrected bugs) to the merge-commit-message. This can be taken from the **briefly-list-the-changes** above (best case) or the separate commit messages (worst case).

2024-12-16 13:35 UTC, reneSchm commented on cpp/models/d_abm/quad_well.h
> +            //m_adoption_rates[{r.region, r.from, r.to}] = r;
```suggestion
```

2025-01-08 16:27 UTC, reneSchm requested changes
I seem to barely document code I write under a deadline. I will continue this with more suggestions later, but feel free to edit them - or add your own documentation, there is a lot to do...

The directory structure and naming looks pretty good. I have not checked the tests yet

2025-01-08 16:27 UTC, reneSchm commented on cpp/models/d_abm/model.h
> +};
Whoever would write all of this without a singular comment?
```suggestion

/**
 * @brief Wrap an implementation of a diffusive ABM so it can be run by the d_abm::Simulation.
 * Uses the CRTP. See comments on using statements for expected function signatures.
 * @tparam Implementation A class implementing all functions and types marked with the using keyword in Model.
 */
template <class Implementation>
class Model : public Implementation
{
public:
    /// Use the constructors defined by the Implementation
    using Implementation::Implementation;

    /**
     * @brief Set the status of an agent.
     * Expected signature: `void adopt(Agent&, const Status&)`
     */
    using Implementation::adopt;

    /**
     * @brief Calculate the current adoption rate of an agent from its status to the given one.
     * Expected signature: `double adoption_rate(const Agent&, const Status&)`
     */
    using Implementation::adoption_rate;

    /**
     * @brief Change the Position of an Agent, depending on its state, the current time and step size.
     * Expected signature: `void move(const double, const double, Agent&)`
     * The first argument is time, the second step size.
     */
    using Implementation::move;

    /**
     * @brief Get the Implementations RNG.
     * Expected signature: `mio::RandomNumberGenerator& get_rng()`
     */
    using Implementation::get_rng;

    /**
     * @brief Aggregate the population by their Status for the simulation result.
     * Expected signature: `Eigen::VectorXd time_point()`
     */
    using Implementation::time_point;

    /// @brief The status of an agent.
    using Status = typename Implementation::Status;
    /// @brief An agent is expected to contain at least a status and a position.
    using Agent = typename Implementation::Agent;

    /// @brief Empty function for compatability with MEmilio.
    inline constexpr void check_constraints() const
    {
    }
};```

2025-01-16 15:17 UTC, reneSchm commented on cpp/tests/test_d_abm_model.cpp
> +    EXPECT_EQ(well, size_t(0));
Test 1-3 as well?

2025-01-16 15:21 UTC, reneSchm commented on cpp/tests/test_d_abm_model.cpp
> +    EXPECT_EQ(qw.adoption_rate(a1, InfectionState::E), 0.025);
Other branches that are not checked are
- the rate for a2 to E is 0
- another isolated infected does not influence the rate
- the rate of a1 scales correctly with more nearby infected and non-infected

2025-01-16 15:24 UTC, reneSchm commented on cpp/tests/test_d_abm_model.cpp
> +    EXPECT_EQ(a2.position[1], 1);
This should not work well without mocking, as move uses a normal distributed value.

2025-01-16 15:27 UTC, reneSchm commented on cpp/models/d_abm/quad_well.h
> +            }
Do we want to keep these counters?

2025-01-27 14:04 UTC, reneSchm commented on cpp/models/smm/parameters.h
> +template <class Status>
```suggestion
/**
 * @brief Struct defining a possible regional transition in a Model based on Poisson Processes.
 * @tparam Status An infection state enum.
 */
template <class Status>
```

2025-01-28 15:22 UTC, jubicker commented on cpp/tests/test_d_abm_model.cpp
> +    EXPECT_EQ(a2.position[1], 1);
It does because sigma is 0, therefore the movement is only defined by the function gradient.

2025-01-29 08:01 UTC, reneSchm commented on cpp/tests/test_d_abm_model.cpp
> +    EXPECT_EQ(a2.position[1], 1);
Oh, I missed that. Can you add a comment that sigma=0? It is not that obvious from the constructor call.

2025-01-29 08:44 UTC, jubicker commented on cpp/models/d_abm/quad_well.h
> +            }
I would say yes. They might be helpful for output analysis.

2025-01-31 14:48 UTC, reneSchm requested changes

2025-01-31 14:48 UTC, reneSchm commented on cpp/tests/test_smm_model.cpp
> +TEST(TestSMMSimulation, covergence)
```suggestion
TEST(TestSMMSimulation, convergence)
```

2025-01-31 14:48 UTC, reneSchm commented on cpp/tests/test_smm_model.cpp
> +    EXPECT_GE(rel_diff1, rel_diff2);
Why do you compare the two models with each other rather than with the expected result? The tolerance for comparing with the result is probably fairly large, but I think it would be better than comparing two "random" values.

Also, why the greater equal? If both models converge, reldiff1 < rel_diff2 should be possible, right? Maybe use one model, and compare the simulated rate against the expected rate, with some tolerance (with can be fairly large).

2025-01-31 14:48 UTC, reneSchm commented on cpp/tests/test_smm_model.cpp
> +    EXPECT_GE(rel_diff1, rel_diff2);
Moreover, should this be a random test perhaps? So that it checks not only that one specific seed works. It is okay for a random test to possibly fail, if it is very unlikely that it does. You can run it a couple 1000 times to check that the tolerance is large enough for most edge cases.

2025-01-31 15:04 UTC, reneSchm commented on cpp/tests/test_d_abm_model.cpp
> +    EXPECT_EQ(qw.adoption_rate(a1, InfectionState::E), 0.025);
Can you add descriptions to the test what it is you check? Otherwise it is hard to tell what is going on here.

This is true for all added tests. For example, in TestQuadWell.well(_index ?) one comment at the top like "check that well_index returns indices in the correct order" would be enough.
Here, in TestQuadWell.adoptionRate, you could write down what the agents and rates are used for, and/or explain what the EXPECTs do. Like "check that a1 is affected by a2, but not the for off a3" for the first EXPECT call, and so on.

2025-01-31 15:36 UTC, jubicker commented on cpp/tests/test_smm_model.cpp
> +    EXPECT_GE(rel_diff1, rel_diff2);
What I do here is check whether the simulated transition rate converges to the expected transition rate for num_runs, pop_size to infty. And I realize this by checking whether the relative difference between the simulated number of transitions and the expected number of transitions gets smaller if I increase the number of runs as well as the number of agents.

I can also only use one model and compare the simulated and expected number of transitions, but what would be an appropriate tolerance? 1%, 50%? An how many runs do we require to meet that tolerance?

2025-02-05 09:55 UTC, jubicker commented on cpp/memilio/epidemiology/adoption_rate.h
> +    std::vector<Influence<Status>> influences;
Now we do

2025-02-13 09:01 UTC, jubicker commented on cpp/models/d_abm/parameters.h
We decided to keep this file and add a comment on why it is empty.

2025-02-13 13:16 UTC, reneSchm commented on cpp/models/d_abm/quad_well.h
> +                m_number_transitions[static_cast<size_t>(agent.status)](old_well, new_well)++;
Can you add an agent (or change ones position) in the move test, so this line gets covered? Maybe check as well that number transitions = 0,...,0,1,0,...,0

2025-02-13 13:26 UTC, reneSchm commented on cpp/tests/test_smm_model.cpp
> +    EXPECT_LE(rel_dev, 0.15);
Nice, 15% is honestly better than I expected.

2025-02-13 15:19 UTC, reneSchm approved these changes

2025-02-13 15:21 UTC, merged