1167 Update some dependencies
SciCompMod/memilio pull request #1168
Opened 2024-12-19 16:22 UTC by reneSchm

# Changes and Information

Please **briefly list the changes** (main added features, changed items, or corrected bugs) made:

- Update minimum required cmake 3.11 -> 3.13
- Update spdlog 1.11.0 -> 1.15.0
- Update Eigen 3.3.9 -> 3.4.0
- Update JsonCpp 1.9.5 -> 1.9.6

If need be, add additional information and what the reviewer should look out for in particular:

- These updates help with support of recent compiler versions 
- cmake 3.13 was already required by install in cpp/CMakeLists.txt:183, prior versions are unable to install targets from a subdirectory 
- A newer spdlog version is required unless we want to silence several compiler warnings when including the library with gcc 14+. chose newest release, though we may use an older one if there is a reason for it
- Eigen 3.4.0 is newest release, but already 2 years old. It adds more compatibility with STL, e.g. iterators and initializer list support.
  - **IMPORTANT**: now including Eigen as system library to avoid several compiler warnings from within the library. could use several pragmas to silence each error individually instead
  - Eigen 4.0.0 may be available soon<sup>(TM)</sup>
- JsonCpp 1.9.6 has several bugfixes, though we are not affected by these bugs (AFAIK)
- Check commits for steps taken to update the code to these versions. Updates are independent and can be selectively undone, if desired 
  - changes to the serialization test are due to stricter is_container requirement, causing std::array to be serialized as tuple. deserialization of std::array was not supported anyways, so this is not a breaking change
 
## Merge Request - Guideline Checklist

Please check our [git workflow](https://github.com/SciCompMod/memilio/wiki/git-workflow). Use the **draft** feature if the Pull Request is not yet ready to review.

### Checks by code author

- [x] Every addressed issue is linked (use the "Closes #ISSUE" keyword below)
- [x] New code adheres to [coding guidelines](https://github.com/SciCompMod/memilio/wiki/Coding-guidelines)
- [x] No large data files have been added (files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [x] Tests are added for new functionality and a local test run was successful (with and without OpenMP)
- [x] Appropriate **documentation** for new functionality has been added (Doxygen in the code and Markdown files if necessary)
- [x] Proper attention to licenses, especially no new third-party software with conflicting license has been added
- [ ] (For ABM development) Checked [benchmark results](https://github.com/SciCompMod/memilio/wiki/Agent-Based-Model-Development) and ran and posted a local test above from before and after development to ensure performance is monitored.

### Checks by code reviewer(s)

- [ ] Corresponding issue(s) is/are linked and addressed
- [ ] Code is clean of development artifacts (no deactivated or commented code lines, no debugging printouts, etc.)
- [ ] Appropriate **unit tests** have been added, CI passes, code coverage and performance is acceptable (did not decrease)
- [ ] No large data files added in the whole history of commits(files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [ ] On merge, add 2-5 lines with the changes (main added features, changed items, or corrected bugs) to the merge-commit-message. This can be taken from the **briefly-list-the-changes** above (best case) or the separate commit messages (worst case).

Closes #1167

2025-01-02 15:15 UTC, mknaranja commented
@reneSchm Please update readmes :)

2025-01-02 18:57 UTC, mknaranja requested changes
Thank you for the updates. I gave some more or less informed comments. Maybe check for them, update the readmes and then it should be OK.

2025-01-02 18:57 UTC, mknaranja commented on cpp/memilio/utils/logging.h
> -};
don't see why so much became superfluous?!

2025-01-02 18:57 UTC, mknaranja commented on cpp/tests/abm_helpers.cpp
> -    local_air_exposure.resize({mio::abm::CellIndex(location.get_cells().size()), mio::abm::VirusVariant::Count});
have you checked that there are no other relevant resizes that need to be changed?

2025-01-02 18:57 UTC, mknaranja commented on cpp/memilio/utils/uncertain_value.h
> +double format_as(const UncertainValue<FP>& uv)
don't we then also need a format_as for an ad type with UV and derivative?

2025-01-03 09:28 UTC, reneSchm commented on cpp/memilio/math/stepper_wrapper.h
> +                          boost::numeric::odeint::initially_resizer>>;
This replaces the line `dxds.resizeLike(x);` in the step method. The initially_resizer used to fail (silently) to resize the vector with the older Eigen version. But after the update, the resizers (in part. initially_resize) defined in the newly included boost header (line 27, eigen_resize.hpp) work as intended.

There are never_resize, initially_resize and always_resize. When try_step is called, boost resizes x and dxds never, the first time, or always respectively. I assume here that the vector sizes should not change, as the result TimeSeries would have issues with that anyways, hence I chose initially_resize.

2025-01-03 09:31 UTC, reneSchm commented on cpp/memilio/math/stepper_wrapper.h
> -                        dxds.resizeLike(x); // boost resizers cannot resize Eigen::Vector, hence we need to do that here
I did not update boost, but the "new" Eigen version (it is 2 years old now) works better with boost, see response to the resizers above.

2025-01-03 09:56 UTC, reneSchm commented on cpp/tests/abm_helpers.cpp
> -    local_air_exposure.resize({mio::abm::CellIndex(location.get_cells().size()), mio::abm::VirusVariant::Count});
Yes, we don't resize CustomIndexArray that much anyways. Also, if it were used incorrectly somewhere, the compiler would complain, vehemently.

2025-01-03 12:36 UTC, reneSchm commented on cpp/memilio/utils/custom_index_array.h
> +     ' Note that when increasing the overall size, new values may be uninitialized.
The internal array is stored linearly and reduced (or extended) to the product of all dimensions. So your 3x3 matrix is really just an array (1 2 3 4 5 6 7 8 9), with matrix accessor. So resizing to 1x9 or 9x1 would leave the array untouched. If we cut that matrix to 
- 3x2, we get 
1 2
3 4
5 6 
- 3x1, we get 
1
2
3
- 2x3, we get
1 2 3
4 5 6
- 2x2, we get
1 2
3 4

2025-01-03 12:47 UTC, reneSchm commented on cpp/memilio/utils/uncertain_value.h
> +double format_as(const UncertainValue<FP>& uv)
Good catch, that "double" should be a "FP" (or better "const FP&"). fmt is able to call the AD format_as if an AD type is returned here.

2025-01-03 12:58 UTC, reneSchm commented on cpp/memilio/utils/logging.h
> -};
Two things. First, since we only print the value part of the AD type, I use a simpler part of the [fmt API](https://fmt.dev/latest/api/#formatting-user-defined-types), i.e. format_as,  to do essentially the same as this struct in fewer lines.
Second, I used the same template deduction @lenaploetzke introduced in #1155 to handle both (probably all) AD types, hence there is only one function replacing both types.

2025-01-03 16:29 UTC, reneSchm commented
Thanks for the review @mknaranja. Please check the "additional information for reviewers", in case you haven't.

I had made Eigen a system library, so we do not need to manually add compiler diagnostics. I hadn't removed them before your review ([see here](https://github.com/SciCompMod/memilio/pull/1168/commits/46d0ef9ca9cff999280700adf02f5b1402344ffb#diff-f86e6cb1e4100691d5ccc19e29cb4d613d8a8dd92c4e336170edce5324041f0cR24)).

I also replaced mio::Vector by Eigen::VectorX (new in 3.4.0) in that commit, so it is more obvious that Vector is a Eigen type and not something we wrote ourselves.

2025-01-03 16:56 UTC, mknaranja commented on cpp/memilio/utils/custom_index_array.h
> +     ' Note that when increasing the overall size, new values may be uninitialized.
I was expecting that. Is that really expected behavior for a (new) user? Shouldn't we avoid sizing down with keeping the values as this is normally not what you what want when reducing dimensions?

2025-01-03 18:59 UTC, mknaranja reviewed
Looks good. There is just one comment / discussion we should agree on.

2025-01-06 15:07 UTC, mknaranja approved these changes

2025-01-06 15:09 UTC, merged