130 unqualified try except
SciCompMod/memilio pull request #174
Opened 2022-01-18 14:00 UTC by annette-lutz

## Merge Request - GuideLine Checklist 

**Guideline** to check code before resolve WIP and approval, respectively.
As many checkboxes as possible should be ticked.

### Checks by code author:
* [x] There is at least one issue associated with the pull request.
* [x] The branch follows the naming conventions as defined in the [git workflow](git-workflow).
* [x] New code adheres with the [coding guidelines](coding-guidelines)
* [ ] Tests for new functionality has been added
* [x] A local test was succesful
* [ ] There is appropriate **documentation** of your work. (use doxygen style comments)
* [ ] If new third party software is used, did you pay attention to its license? Please remember to add it to the wiki after successful merging.
* [ ] If new mathematical methods or epidemiological terms are used, has the glossary been updated ? Did you provide further documentation ?
 is present or referenced. Please provide your references.
* [ ] The following questions are addressed in the documentation*:  Developers (what did you do?, how can it be maintained?), For users (how to use your work?), For admins (how to install and configure your work?)
* For documentation: Please write or update the Readme in the current working directory!

### Checks by code reviewer(s):
* [x] Is the code clean of development artifacts e.g., unnecessary comments, prints, ...
* [x] The ticket goals for each associated issue are reached or problems are clearly addressed (i.e., a new issue was introduced).
* [x] There are appropriate **unit tests** and they pass.
* [x] The git history is clean and linearized for the merge request.
* [x] Coverage report for new code is acceptable.

2022-01-20 12:38 UTC, mknaranja commented
@dabele Could you take over?

2022-01-20 12:44 UTC, dabele commented
> @dabele Could you take over the review ?

no problem

2022-01-20 14:03 UTC, dabele requested changes

2022-01-25 10:56 UTC, annette-lutz commented on pycode/memilio-epidata/memilio/epidata_test/test_epidata_getDataIntoPandasDataFrame.py
> +        self.assertEqual(str(error.exception), error_message)
Yes, that would be better.

2022-01-25 10:57 UTC, annette-lutz commented on pycode/memilio-epidata/memilio/epidata/getVaccinationData.py
> +class DataError(Exception):
Moved it to getDataIntoPandasDataFrame and used it instead of AssertionError or ValueError.

2022-01-25 10:57 UTC, annette-lutz commented on pycode/memilio-epidata/memilio/epidata/getRKIData.py
> +            raise FileExistsError("Error: The file: " + file_in + \
changed it

2022-01-25 10:57 UTC, annette-lutz commented on pycode/memilio-epidata/memilio/epidata/getDIVIData.py
> +        raise TypeError("Error: no dataframe given.") from err
Removed try except clause. I also removed check whether the return value is a dataframe in getCommuterMobility.

2022-01-25 10:57 UTC, annette-lutz commented on pycode/memilio-epidata/memilio/epidata/getDIVIData.py
> +            raise FileExistsError("Error: The file: " + file_in + \
changed it

2022-01-25 10:57 UTC, annette-lutz commented on pycode/memilio-epidata/memilio/epidata/getCommuterMobility.py
> +        raise AssertionError("Error. ")
Changed it to DataError.

2022-01-25 10:57 UTC, annette-lutz commented on pycode/memilio-epidata/memilio/epidata/getCommuterMobility.py
> +        raise AssertionError("Error. ")
done

2022-01-25 10:58 UTC, annette-lutz commented on pycode/memilio-epidata/memilio/epidata/getCommuterMobility.py
> +                out_folder=out_folder, merge_eisenach=False, write_df=True)
done

2022-01-25 13:27 UTC, dabele approved these changes

2022-01-25 13:28 UTC, merged