677 final version secir reproduction number
SciCompMod/memilio pull request #858
Opened 2023-12-04 14:24 UTC by johapau

# Changes and Information

Please **briefly list the changes** made, additional Information and what the Reviewer should look out for:

-

## Merge Request - Guideline Checklist

Please check our [git workflow](https://github.com/SciCompMod/memilio/wiki/git-workflow). Use the **draft** feature if the Pull Request is not yet ready to review.

### Checks by code author

- [x] Every addressed issue is linked (use the "Closes #ISSUE" keyword below)
- [x] New code adheres to [coding guidelines](https://github.com/SciCompMod/memilio/wiki/Coding-guidelines)
- [x] No large data files have been added (files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [x] Tests are added for new functionality and a local test run was successful
- [x] Appropriate **documentation** for new functionality has been added (Doxygen in the code and Markdown files if necessary)
- [x] Proper attention to licenses, especially no new third-party software with conflicting license has been added
- [x] (For ABM development) Checked [benchmark results](https://github.com/SciCompMod/memilio/wiki/Agent-Based-Model-Development)

### Checks by code reviewer(s)

- [x] Corresponding issue(s) is/are linked and addressed
- [x] Code is clean of development artifacts (no deactivated or commented code lines, no debugging printouts, etc.)
- [x] Appropriate **unit tests** have been added, CI passes and code coverage is acceptable (did not decrease)
- [x] No large data files added in the whole history of commits(files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)

2023-12-05 14:05 UTC, HenrZu requested changes

2023-12-05 14:05 UTC, HenrZu commented on cpp/tests/test_odesecir.cpp
> +    model.populations[{mio::AgeGroup(0), mio::osecir::InfectionState::Susceptible}]        = 3000;
Just to counteract possible errors: I would also set the Confirmed Compartments to 0

2024-01-05 10:03 UTC, HenrZu approved these changes

2024-01-05 12:34 UTC, mknaranja commented on cpp/models/ode_secir/model.h
> +                test_and_trace_required > 5 * params.template get<TestAndTraceCapacity>()) {
For all models, we should add parameters that describe the multiplicative factor used for the TestAndTraceCapacity as we use different realizations in secir and secirvvs simulations. This is inconsistent but not a problem from this new feature.

2024-01-05 12:40 UTC, merged