885 Compatibility of costum simulation and advance functions with flows
SciCompMod/memilio pull request #889
Opened 2024-01-12 13:59 UTC by HenrZu

# Changes and Information

Please **briefly list the changes** made, additional Information and what the Reviewer should look out for:

-

## Merge Request - Guideline Checklist

Please check our [git workflow](https://github.com/SciCompMod/memilio/wiki/git-workflow). Use the **draft** feature if the Pull Request is not yet ready to review.

### Checks by code author

- [ ] Every addressed issue is linked (use the "Closes #ISSUE" keyword below)
- [ ] New code adheres to [coding guidelines](https://github.com/SciCompMod/memilio/wiki/Coding-guidelines)
- [ ] No large data files have been added (files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [ ] Tests are added for new functionality and a local test run was successful
- [ ] Appropriate **documentation** for new functionality has been added (Doxygen in the code and Markdown files if necessary)
- [ ] Proper attention to licenses, especially no new third-party software with conflicting license has been added
- [ ] (For ABM development) Checked [benchmark results](https://github.com/SciCompMod/memilio/wiki/Agent-Based-Model-Development) and ran and posted a local test above from before and after development to ensure performance is monitored.

### Checks by code reviewer(s)

- [ ] Corresponding issue(s) is/are linked and addressed
- [ ] Code is clean of development artifacts (no deactivated or commented code lines, no debugging printouts, etc.)
- [ ] Appropriate **unit tests** have been added, CI passes, code coverage and performance is acceptable (did not decrease)
- [ ] No large data files added in the whole history of commits(files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)

2024-01-15 15:42 UTC, reneSchm requested changes
Looks good, but please review the documentation:
Almost all doc strings are missing `@brief` and `@return`, as well as `[in]` and `[out}` notes on the params.

2024-01-15 15:42 UTC, reneSchm commented on cpp/models/ode_secir/model.h
> + * Specialization of FlowSimulation for SECIR models using Simulation.
this specializes the function, not the model

2024-01-16 08:30 UTC, mknaranja approved these changes

2024-01-16 08:31 UTC, reneSchm approved these changes

2024-01-16 08:40 UTC, merged