793 add seasonality to ide model
SciCompMod/memilio pull request #972
Opened 2024-03-20 09:25 UTC by lenaploetzke

# Changes and Information

Please **briefly list the changes** (main added features, changed items, or corrected bugs) made:

- Functionality to simulate the IDE model with a seasonality has been added.
- The test for the function check_constraints() of the Parameters class was rewritten. The use of the class Model made the test unnecessarily complicated.

## Merge Request - Guideline Checklist

Please check our [git workflow](https://github.com/SciCompMod/memilio/wiki/git-workflow). Use the **draft** feature if the Pull Request is not yet ready to review.

### Checks by code author

- [ ] Every addressed issue is linked (use the "Closes #ISSUE" keyword below)
- [ ] New code adheres to [coding guidelines](https://github.com/SciCompMod/memilio/wiki/Coding-guidelines)
- [ ] No large data files have been added (files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [ ] Tests are added for new functionality and a local test run was successful (with and without OpenMP)
- [ ] Appropriate **documentation** for new functionality has been added (Doxygen in the code and Markdown files if necessary)
- [ ] Proper attention to licenses, especially no new third-party software with conflicting license has been added
- [ ] (For ABM development) Checked [benchmark results](https://github.com/SciCompMod/memilio/wiki/Agent-Based-Model-Development) and ran and posted a local test above from before and after development to ensure performance is monitored.

### Checks by code reviewer(s)

- [ ] Corresponding issue(s) is/are linked and addressed
- [ ] Code is clean of development artifacts (no deactivated or commented code lines, no debugging printouts, etc.)
- [ ] Appropriate **unit tests** have been added, CI passes, code coverage and performance is acceptable (did not decrease)
- [ ] No large data files added in the whole history of commits(files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [ ] On merge, add 2-5 lines with the changes (main added features, changed items, or corrected bugs) to the merge-commit-message. This can be taken from the **briefly-list-the-changes** above (best case) or the separate commit messages (worst case).

Closes #793.

2024-03-21 08:38 UTC, reneSchm requested changes

2024-03-22 14:25 UTC, lenaploetzke commented on cpp/examples/ide_secir.cpp
> +    model.parameters.set<mio::isecir::StartDay>(40);
I talked to @annawendler and removed t0 so that there are no conflicts anymore. 
I think the naming of the parameter is still ok.

2024-03-25 12:47 UTC, reneSchm requested changes
Good work! There are only two comments that could be updated, then we're done here.

2024-03-25 12:47 UTC, reneSchm commented on cpp/models/ide_secir/simulation.h
>   */
I made a small update to this description in another branch, for consistency you could use
```cpp
/**
 * @brief Run a Simulation of a mio::isecir::Model.
 * To set the start time t0, use the model parameter StartDay.
 * @param[in] tmax End time.
 * @param[in] dt Initial step size of integration.
 * @param[in] model An instance of mio::isecir::Model.
 * @return A TimeSeries to represent the final simulation result
 */
```

2024-04-02 10:13 UTC, reneSchm approved these changes

2024-04-02 10:17 UTC, merged