990 run 2021 simulation in python
SciCompMod/memilio pull request #991
Opened 2024-04-04 13:33 UTC by MaxBetzDLR

# Changes and Information

Please **briefly list the changes** (main added features, changed items, or corrected bugs) made:

- simulation of 2021 paper 

If need be, add additional information and what the reviewer should look out for in particular:

- Some dampings are not used in cpp and thus are commented out in python aswell

## Merge Request - Guideline Checklist

Please check our [git workflow](https://github.com/SciCompMod/memilio/wiki/git-workflow). Use the **draft** feature if the Pull Request is not yet ready to review.

### Checks by code author

- [ ] Every addressed issue is linked (use the "Closes #ISSUE" keyword below)
- [ ] New code adheres to [coding guidelines](https://github.com/SciCompMod/memilio/wiki/Coding-guidelines)
- [ ] No large data files have been added (files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [ ] Tests are added for new functionality and a local test run was successful (with and without OpenMP)
- [ ] Appropriate **documentation** for new functionality has been added (Doxygen in the code and Markdown files if necessary)
- [ ] Proper attention to licenses, especially no new third-party software with conflicting license has been added
- [ ] (For ABM development) Checked [benchmark results](https://github.com/SciCompMod/memilio/wiki/Agent-Based-Model-Development) and ran and posted a local test above from before and after development to ensure performance is monitored.

### Checks by code reviewer(s)

- [ ] Corresponding issue(s) is/are linked and addressed
- [ ] Code is clean of development artifacts (no deactivated or commented code lines, no debugging printouts, etc.)
- [ ] Appropriate **unit tests** have been added, CI passes, code coverage and performance is acceptable (did not decrease)
- [ ] No large data files added in the whole history of commits(files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [ ] On merge, add 2-5 lines with the changes (main added features, changed items, or corrected bugs) to the merge-commit-message. This can be taken from the **briefly-list-the-changes** above (best case) or the separate commit messages (worst case).

2024-04-04 13:38 UTC, MaxBetzDLR commented
Simulation creates following gif:
![simulation](https://github.com/SciCompMod/memilio/assets/104758467/68477538-97b0-43c5-bfd6-9e5f6dbeeea1)

2024-04-10 07:03 UTC, HenrZu requested changes
Thanks for the great extension :) Looks very good. A few small comments. Also, we should save & compare the graphs in cpp and py before merging again.

2024-04-22 14:17 UTC, HenrZu approved these changes
very good work! :)

2024-04-22 19:31 UTC, HenrZu requested changes

2024-04-22 19:31 UTC, HenrZu commented on pycode/examples/simulation/2021_vaccination_sarscov2_delta_germany.py
> +                                                                            [Location.School.value], group_weights_all)
```suggestion
        params.ContactPatterns.school_holiday_damping = mio.DampingSampling(school_holiday_value, InterventionLevel.Holidays.value,
                                                                            Intervention.SchoolClosure.value, 0.0,
                                                                            [Location.School.value], group_weights_all)
```

2024-04-24 07:36 UTC, merged